GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/1

###
DELETE http://localhost:3001/api/persons/65de0a34e6b05b830a667977

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Adan Guerra", 
    "number": "040-123456"
}